### ISSUE TITLE
Using the Fallout 4 Terminal Theme

### ISSUE THREAD

**Issue by RogueWipplash** [CommandCrafterHD/Fallout4TerminalTheme#10]
When I enable the Fallout 4 Terminal Theme I am in capable of selecting my servers, the rest of Discord works properly. I have tried repairing Better Discord, Deleting Better Discord, Reinstalling Better Discord, and Clean installing the theme. None of this enables me to select my servers, so currently I am forced to disable the theme, select the server I want to open, then enable the theme.

**Comment by Cubjay69** [comment]
seconded, Just disable themes or use another for time being

**Comment by CommandCrafterHD** [comment]
Fixed in Version 1.2.2 onwards

Also, because GitHub doesn't notify me of issues created in my Repos, please contact me on discord directly with breaking issues so I can fix them faster :)
