### ISSUE TITLE
Issue when editing comments

### ISSUE THREAD

**Issue by JuniSupreme** [CommandCrafterHD/Fallout4TerminalTheme#16]
Everything works fine until I try and edit the middle or beginning of a comment. I highlight the comment, but once I type, the letters just stay there as it essentially phantom types invisible words over the original message (which dont change even if I click to save it anyways)... It works fine when editing the end of the sentence however. I have to retype the whole sentence to fix an error which im sure isnt suppose to happen.

**Comment by CommandCrafterHD** [comment]
Hmm, I can't recreate this, are you using any other themes or plugins together with the theme?
