### ISSUE TITLE
Server List is not clickable

### ISSUE THREAD

**Issue by Davoleo** [CommandCrafterHD/Fallout4TerminalTheme#6]
Hey, I'm using this theme on [Powercord](https://powercord.dev) + Discord Canary after adding a powercord Manifest for it.
So far the plugin worked completely fine, although today I faced the issue of not being able to click on the server bar.
I don't know if this also happens on BD, or if it's just a Powercord issue, in case you don't want to support canary and powercord it's fine but it'd also be a pity since, except for this issue and some few issues with buttons the theme works out of the box with canary.

Cloned theme repo:
![image](https://user-images.githubusercontent.com/24458276/134480832-2a02f099-f2ea-4c82-a6f1-89d3e6aadda1.png)

**Comment by PyroSimba** [comment]
This issue exists on BetterDiscord too. Just started happening to me today :(

**Comment by brenmadeit** [comment]
same with normal discord. other themes from betterdiscord works just this one only

**Comment by axcyia** [comment]
having the same issue on BetterDiscord...

**Comment by Davoleo** [comment]
Ok seems like the latest commit fixed this issue, thanks @CommandCrafterHD
